import { createContext, useContext, useEffect, useState } from 'react';
import type { ReactNode } from 'react';

export type Language = 'en' | 'np';

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.members': 'Members',
    'nav.contact': 'Contact',
    'nav.terms': 'Terms & Conditions',
    'nav.login': 'Login',
    'nav.language': 'Language',
    'nav.english': 'English',
    'nav.nepali': 'नेपाली',
    'nav.primaryNavigation': 'Primary navigation',
    'nav.toggleMenu': 'Toggle menu',
    'brand.name': 'Hamro Samuh',
    'brand.tagline': 'Together We Grow',

    'footer.description': 'At Hamro Samuh, we believe that every small contribution has the power to create meaningful change. By combining the strength of our members with transparent financial management, responsible savings, and community-focused lending, we work together to improve lives, encourage economic stability, and build a prosperous future rooted in trust, unity, and mutual support.',
    'footer.socialLinks': 'Social media links',
    'footer.quickLinks': 'Quick Links',
    'footer.contactUs': 'Contact Us',
    'footer.address': 'Shankarsaraiya, Birgunj, Nepal',
    'footer.phone': '+977 9823092963',
    'footer.rights': 'All rights reserved.',

    'home.hero.preTitle': 'Together We Grow',
    'home.hero.title': 'Stronger Together',
    'home.hero.description': 'A community savings platform designed to bring people together, build trust and create a better financial future for everyone.',
    'home.hero.join': 'Join Our Samuh',
    'home.hero.login': 'Member Login',
    'home.services.heading': 'Everything You Need to Manage Savings',
    'home.service.monthlySavings.title': 'Monthly Savings',
    'home.service.monthlySavings.desc': 'Members can deposit their savings every month easily and securely.',
    'home.service.transparentRecords.title': 'Transparent Records',
    'home.service.transparentRecords.desc': 'Every transaction is recorded and can be viewed anytime.',
    'home.service.memberManagement.title': 'Member Management',
    'home.service.memberManagement.desc': 'Easy registration and management of all members.',
    'home.service.financialReports.title': 'Financial Reports',
    'home.service.financialReports.desc': 'Generate reports for savings, balances and transactions.',
    'home.service.secureData.title': 'Secure Data',
    'home.service.secureData.desc': 'Member information and financial records are stored securely.',
    'home.service.onlineAccess.title': 'Online Access',
    'home.service.onlineAccess.desc': 'Access your account and transaction history anytime, anywhere.',
    'home.stats.activeMembers': 'Active Members',
    'home.stats.totalSavings': 'Total Savings',
    'home.stats.monthlyCollections': 'Monthly Collections',
    'home.stats.successfulTransactions': 'Successful Transactions',
    'home.about.heading': 'HAMRO SAMUH',
    'home.about.text': 'Hamro Samuh is a community-based savings organization that encourages members to save money regularly in a secure and transparent manner. Our goal is to promote financial discipline, mutual support, and economic growth within our community.',
    'home.learnMore': 'Learn More →',
    'home.howItWorks': 'HOW IT WORKS',
    'home.step.register': 'Register',
    'home.step.register.desc': 'Become a member of Hamro Samuh.',
    'home.step.saveMoney': 'Save Money',
    'home.step.saveMoney.desc': 'Deposit your monthly savings.',
    'home.step.trackSavings': 'Track Your Savings',
    'home.step.trackSavings.desc': 'View your savings and transaction history online.',
    'home.step.achieveGoals': 'Achieve Your Goals',
    'home.step.achieveGoals.desc': 'Build financial security through consistent saving.',
    'home.testimonials': 'TESTIMONIALS',
    'home.testimonial.sita': 'Hamro Samuh has helped me develop the habit of saving every month.',
    'home.testimonial.ram': 'The online system makes it easy to track my savings.',
    'home.testimonial.alok': 'Regular saving feels simple and achievable with Hamro Samuh.',
    'home.testimonial.amit': 'I appreciate having clear and transparent records of my savings.',
    'home.testimonial.jhalak': 'The support from the community keeps me motivated to save.',
    'home.testimonial.sailendra': 'Hamro Samuh makes it easier to plan for a more secure future.',
    'home.member': 'Member',
    'home.announcements': 'ANNOUNCEMENTS',
    'home.announcement.monthlyMeeting': 'Monthly Meeting',
    'home.announcement.monthlyMeeting.desc': 'Monthly meeting will be held on 15th of every month.',
    'home.announcement.newFeature': 'New Feature',
    'home.announcement.newFeature.desc': 'We have introduced online report generation.',
    'home.announcement.holidayNotice': 'Holiday Notice',
    'home.announcement.holidayNotice.desc': 'Office will remain closed on Buddha Purnima.',
    'home.cta.title': 'Ready to Start Your Savings Journey?',
    'home.cta.description': 'Join Hamro Samuh today and take the first step towards a secure financial future.',
    'home.cta.button': 'Become a Member Today',

    'about.hero.description1': 'Hamro Samuh is a community-based organization that brings people together to save regularly, support each other, and build a stronger financial future.',
    'about.hero.description2': 'We believe that when people come together with trust and transparency, small contributions can create a big impact.',
    'about.hero.button': 'Our Members, Our Strength',
    'about.values.heading': 'Our Mission & Values',
    'about.value.togetherness': 'Togetherness',
    'about.value.togetherness.desc': 'We believe in unity and collective growth. Together, we can achieve more.',
    'about.value.trust': 'Trust & Transparency',
    'about.value.trust.desc': 'We operate with honesty and transparency to build strong and lasting relationships.',
    'about.value.empowerment': 'Financial Empowerment',
    'about.value.empowerment.desc': 'We encourage regular saving and smart financial habits for a better tomorrow.',
    'about.value.goal': 'Our Goal',
    'about.value.goal.desc': 'To create a self-reliant community where everyone can grow and prosper.',
    'about.impact.heading': 'Together, we create real impact',
    'about.impact.description': 'Small savings today, stronger community tomorrow.',
    'about.impact.activeMembers': 'Active Members',
    'about.impact.totalSavings': 'Total Savings',
    'about.impact.groups': 'Groups',
    'about.impact.trust': 'Trust & Commitment',
    'about.quote': 'Alone we can do so little; together we can do so much.',

    'services.hero.title': 'Working Together for a Better Tomorrow',
    'services.hero.title.highlight': 'Working Together',
    'services.hero.title.rest': 'for a Better Tomorrow',
    'services.hero.description': 'At Hamro Samuh, we believe that financial growth begins with trust and cooperation. By encouraging regular savings, providing responsible lending, and maintaining transparent financial management, we empower our members to achieve their goals while building a stronger, more resilient community together.',
    'services.hero.button': 'Explore Our Services',
    'services.mission': 'Our Mission',
    'services.mission.description': 'Empowering people and communities through collaboration, support, and sustainable solutions.',
    'services.heading.preTitle': 'WHAT WE DO',
    'services.heading': 'Our Core Services',
    'services.community.title': 'Community Development',
    'services.community.desc': 'We work for the overall development of communities through participation and local empowerment.',
    'services.education.title': 'Education Support',
    'services.education.desc': 'We support quality education by providing resources, training, and opportunities for a better future.',
    'services.health.title': 'Health & Wellness',
    'services.health.desc': 'We promote good health and well-being through awareness programs and health initiatives.',
    'services.livelihood.title': 'Livelihood Support',
    'services.livelihood.desc': 'We help people build skills and access opportunities for sustainable income and growth.',
    'services.advocacy.title': 'Advocacy & Awareness',
    'services.advocacy.desc': 'We raise awareness and advocate for positive change on important social issues.',
    'services.cta.firstTitle': 'Together, we can create',
    'services.cta.firstDescription': 'stronger communities.',
    'services.cta.secondTitle': 'Be part of the change.',
    'services.cta.secondDescription': 'Join us today!',
    'services.cta.button': 'Get Involved',

    'members.heading': 'Our Members',
    'members.role': 'Member',
    'members.since': 'Member since',

    'contact.title': 'Get in',
    'contact.titleHighlight': 'Touch',
    'contact.description': "We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    'contact.formTitle': 'Send us a message',
    'contact.fullName': 'Full Name',
    'contact.email': 'Email Address',
    'contact.message': 'Message',
    'contact.namePlaceholder': 'John Doe',
    'contact.emailPlaceholder': 'john@example.com',
    'contact.messagePlaceholder': 'How can we help you?',
    'contact.send': 'Send Message',
    'contact.notConfigured': 'Message service is not configured. Please try again later.',
    'contact.success': 'Message sent successfully!',
    'contact.failed': 'Failed to send message.',

    'terms.title': 'Terms and',
    'terms.titleHighlight': 'Conditions',
    'terms.subtitle': 'Please read these rules carefully before joining Hamro Samuh.',
    'terms.savings.title': '1. Savings Rules',
    'terms.savings.1': 'No fee is charged when savings are deposited from the 1st to the 10th of the month.',
    'terms.savings.2': 'Savings deposited after the 10th incur a fee of Rs. 100.',
    'terms.savings.3': 'One month: Rs. 100 fee.',
    'terms.savings.4': 'Two months: Rs. 250 fee.',
    'terms.savings.5': 'Three months: Rs. 500 fee.',
    'terms.savings.6': 'If payment is not made for five consecutive months, the member account will be closed. The saved amount will be returned without interest after the group ends.',
    'terms.newMemberLoan.title': 'Loan eligibility for new members',
    'terms.newMemberLoan.1': 'After six months.',
    'terms.loanFine.title': '2. Group Savings, Loan & Fine Rules',
    'terms.loanFine.1': 'If a member does not pay loan installments or monthly savings for two consecutive months, future loans will be limited to a maximum of Rs. 15,000. No loan above this amount will be provided.',
    'terms.loanFine.2': 'If a member does not pay a fine on time, the fine will first be deducted from their annual interest. If the annual interest is insufficient, the remaining fine will be deducted from their principal savings.',
    'terms.loanFine.3': 'If anyone has a problem, please inform the group once. We will review it and make a decision.',
    'terms.meeting.title': '3. Meeting and Loan Rules',
    'terms.meeting.1': 'We meet once every month, on Saturday after the money has been deposited.',
    'terms.meeting.2': 'Anyone who needs a loan should inform the group 7 or 10 days in advance.',
    'terms.meeting.3': 'Rs. 50 is set aside each month to notify group members.',
    'terms.meeting.4': 'Please deposit the service charge (Rs. 150) before taking a loan.',
    'terms.interest.title': '4. Interest Rates',
    'terms.interest.1': 'Loans from Rs. 0 to Rs. 50,000 carry an annual interest rate of 9%.',
    'terms.interest.2': 'Loans above Rs. 50,000 carry an interest rate of 12%.',
    'terms.example.for': 'Example',
    'terms.interest.example': 'For a loan of Rs. 700,000, annual interest is calculated at 9% on Rs. 500,000 and 12% on Rs. 200,000.',
    'terms.newLoan.title': '5. New Member Loan Facility',
    'terms.newLoan.1': 'A new member cannot withdraw a loan during the first six months of joining Hamro Samuh.',
    'terms.newLoan.2': 'A member who saves regularly for six consecutive months and maintains good savings may receive a loan according to their needs.',
    'terms.profit.title': '6. Profit Distribution and Secondary Saving',
    'terms.profit.1': 'It has been decided that 5% of the annual total profit will be saved in the name of Hamro Samuh.',
    'terms.profit.2': 'A person responsible for maintaining the accounts will receive 2% of the annual total profit.',
    'terms.profit.3': 'No fee will be charged for a new person joining Secondary Saving from 2082/10/01 to 2083/09/30. After that period, a fee of Rs. 50 will apply.',
    'terms.secondaryFee.title': 'Secondary Saving Fees',
    'terms.secondaryFee.1': 'A fee of Rs. 20 applies if saving is missed or not deposited in the first month.',
    'terms.secondaryFee.2': 'A fee of Rs. 50 applies in the second month.',
    'terms.secondaryFee.3': 'A fee of Rs. 100 applies in the third month.',
    'terms.secondaryNewLoan.title': '7. Loan for New Secondary Members',
    'terms.secondaryNewLoan.1': 'After completing six months as a member, a person may receive a Secondary Loan of up to Rs. 7,000.',
    'terms.secondaryInterest.title': '8. Secondary Loan and Interest',
    'terms.secondaryInterest.1': 'Loans from Rs. 1,000 to Rs. 10,000 carry an annual interest rate of 9%.',
    'terms.secondaryInterest.2': 'Loans above Rs. 10,000 carry an interest rate of 12%.',
    'terms.secondaryInterest.example.1': 'For a loan of Rs. 20,000, annual interest is calculated at 9% on Rs. 10,000 and 12% on the remaining Rs. 10,000.',
    'terms.secondaryInterest.example.2': 'If the loan cannot be repaid within one year, renewal interest will apply to the outstanding loan amount.',
    'terms.share.title': '9. Share Market',
    'terms.share.1': 'If shares purchased through the Demat accounts provided by members for Hamro Samuh are sold at a profit, 10% of the profit will be given to the relevant member.',
    'terms.share.2': 'If a member in whose name Hamro Samuh opened a Demat account later uses it personally to earn profit, 10% of that profit must be deposited into Hamro Samuh savings.',
    'terms.share.3': 'Please do not use money sent for shares for personal expenses.',
    'terms.date': '2082/09/20',
    'terms.thankYou': 'Thank you',
  },
  np: {
    'nav.home': 'गृहपृष्ठ',
    'nav.about': 'हाम्रो बारेमा',
    'nav.services': 'सेवाहरू',
    'nav.members': 'सदस्यहरू',
    'nav.contact': 'सम्पर्क',
    'nav.terms': 'नियम तथा सर्तहरू',
    'nav.login': 'लगइन',
    'nav.language': 'भाषा',
    'nav.english': 'English',
    'nav.nepali': 'नेपाली',
    'nav.primaryNavigation': 'मुख्य नेभिगेसन',
    'nav.toggleMenu': 'मेनु खोल्नुहोस्',
    'brand.name': 'हाम्रो समूह',
    'brand.tagline': 'सँगै अघि बढौँ',

    'footer.description': 'हाम्रो समूहमा हामी हरेक सानो योगदानले अर्थपूर्ण परिवर्तन ल्याउन सक्छ भन्ने विश्वास गर्छौं। सदस्यहरूको शक्ति, पारदर्शी वित्तीय व्यवस्थापन, जिम्मेवार बचत र समुदायमुखी ऋणलाई जोडेर हामी जीवनस्तर सुधार्न, आर्थिक स्थायित्व बढाउन र विश्वास, एकता तथा पारस्परिक सहयोगमा आधारित समृद्ध भविष्य निर्माण गर्न सँगै काम गर्छौं।',
    'footer.socialLinks': 'सामाजिक सञ्जालका लिङ्कहरू',
    'footer.quickLinks': 'छिटो लिङ्कहरू',
    'footer.contactUs': 'सम्पर्क गर्नुहोस्',
    'footer.address': 'शंकरसरैया, वीरगञ्ज, नेपाल',
    'footer.phone': '+९७७ ९८२३०९२९६३',
    'footer.rights': 'सर्वाधिकार सुरक्षित।',

    'home.hero.preTitle': 'सँगै अघि बढौँ',
    'home.hero.title': 'सँगै अझ बलियो',
    'home.hero.description': 'सबैलाई एकताबद्ध गर्दै विश्वास निर्माण गर्न र राम्रो आर्थिक भविष्य सिर्जना गर्न बनाइएको सामुदायिक बचत मञ्च।',
    'home.hero.join': 'हाम्रो समूहमा जोडिनुहोस्',
    'home.hero.login': 'सदस्य लगइन',
    'home.services.heading': 'बचत व्यवस्थापनका लागि आवश्यक सबै कुरा',
    'home.service.monthlySavings.title': 'मासिक बचत',
    'home.service.monthlySavings.desc': 'सदस्यहरूले हरेक महिना सजिलै र सुरक्षित रूपमा बचत जम्मा गर्न सक्छन्।',
    'home.service.transparentRecords.title': 'पारदर्शी अभिलेख',
    'home.service.transparentRecords.desc': 'हरेक कारोबार अभिलेख गरिन्छ र जुनसुकै बेला हेर्न सकिन्छ।',
    'home.service.memberManagement.title': 'सदस्य व्यवस्थापन',
    'home.service.memberManagement.desc': 'सबै सदस्यको सजिलो दर्ता र व्यवस्थापन।',
    'home.service.financialReports.title': 'वित्तीय प्रतिवेदन',
    'home.service.financialReports.desc': 'बचत, मौज्दात र कारोबारका प्रतिवेदन तयार गर्नुहोस्।',
    'home.service.secureData.title': 'सुरक्षित डाटा',
    'home.service.secureData.desc': 'सदस्यको जानकारी र वित्तीय अभिलेख सुरक्षित रूपमा राखिन्छ।',
    'home.service.onlineAccess.title': 'अनलाइन पहुँच',
    'home.service.onlineAccess.desc': 'जहाँसुकै, जुनसुकै बेला आफ्नो खाता र कारोबार इतिहास हेर्नुहोस्।',
    'home.stats.activeMembers': 'सक्रिय सदस्यहरू',
    'home.stats.totalSavings': 'कुल बचत',
    'home.stats.monthlyCollections': 'मासिक सङ्कलन',
    'home.stats.successfulTransactions': 'सफल कारोबार',
    'home.about.heading': 'हाम्रो समूह',
    'home.about.text': 'हाम्रो समूह एक समुदायमा आधारित बचत संस्था हो, जसले सदस्यहरूलाई सुरक्षित र पारदर्शी तरिकाले नियमित बचत गर्न प्रोत्साहन गर्छ। हाम्रो लक्ष्य समुदायमा वित्तीय अनुशासन, पारस्परिक सहयोग र आर्थिक विकास प्रवर्द्धन गर्नु हो।',
    'home.learnMore': 'थप जान्नुहोस् →',
    'home.howItWorks': 'यसरी काम गर्छ',
    'home.step.register': 'दर्ता गर्नुहोस्',
    'home.step.register.desc': 'हाम्रो समूहको सदस्य बन्नुहोस्।',
    'home.step.saveMoney': 'बचत गर्नुहोस्',
    'home.step.saveMoney.desc': 'आफ्नो मासिक बचत जम्मा गर्नुहोस्।',
    'home.step.trackSavings': 'बचत हेर्नुहोस्',
    'home.step.trackSavings.desc': 'आफ्नो बचत र कारोबार इतिहास अनलाइन हेर्नुहोस्।',
    'home.step.achieveGoals': 'लक्ष्य हासिल गर्नुहोस्',
    'home.step.achieveGoals.desc': 'नियमित बचतबाट वित्तीय सुरक्षा निर्माण गर्नुहोस्।',
    'home.testimonials': 'सदस्यका भनाइहरू',
    'home.testimonial.sita': 'हाम्रो समूहले मलाई हरेक महिना बचत गर्ने बानी विकास गर्न सहयोग गरेको छ।',
    'home.testimonial.ram': 'अनलाइन प्रणालीले मेरो बचत हेर्न सजिलो बनाएको छ।',
    'home.testimonial.alok': 'हाम्रो समूहसँग नियमित बचत सरल र सम्भव महसुस हुन्छ।',
    'home.testimonial.amit': 'मेरो बचतको स्पष्ट र पारदर्शी अभिलेख भएकोमा म खुसी छु।',
    'home.testimonial.jhalak': 'समुदायको सहयोगले मलाई बचत गर्न प्रेरित राख्छ।',
    'home.testimonial.sailendra': 'हाम्रो समूहले सुरक्षित भविष्यको योजना बनाउन सजिलो बनाएको छ।',
    'home.member': 'सदस्य',
    'home.announcements': 'सूचनाहरू',
    'home.announcement.monthlyMeeting': 'मासिक बैठक',
    'home.announcement.monthlyMeeting.desc': 'हरेक महिनाको १५ गते मासिक बैठक बस्नेछ।',
    'home.announcement.newFeature': 'नयाँ सुविधा',
    'home.announcement.newFeature.desc': 'हामीले अनलाइन प्रतिवेदन तयार गर्ने सुविधा ल्याएका छौँ।',
    'home.announcement.holidayNotice': 'बिदा सूचना',
    'home.announcement.holidayNotice.desc': 'बुद्ध पूर्णिमाका दिन कार्यालय बन्द रहनेछ।',
    'home.cta.title': 'आफ्नो बचत यात्रा सुरु गर्न तयार हुनुहुन्छ?',
    'home.cta.description': 'आजै हाम्रो समूहमा जोडिनुहोस् र सुरक्षित आर्थिक भविष्यतर्फ पहिलो कदम चाल्नुहोस्।',
    'home.cta.button': 'आजै सदस्य बन्नुहोस्',

    'about.hero.description1': 'हाम्रो समूह एक समुदायमा आधारित संस्था हो, जसले मानिसहरूलाई नियमित बचत गर्न, एकअर्कालाई सहयोग गर्न र बलियो आर्थिक भविष्य निर्माण गर्न एकताबद्ध गर्छ।',
    'about.hero.description2': 'विश्वास र पारदर्शिताका साथ मानिसहरू एकजुट हुँदा सानो योगदानले ठूलो प्रभाव पार्न सक्छ भन्ने हाम्रो विश्वास छ।',
    'about.hero.button': 'हाम्रा सदस्य, हाम्रो शक्ति',
    'about.values.heading': 'हाम्रो लक्ष्य तथा मूल्यहरू',
    'about.value.togetherness': 'एकता',
    'about.value.togetherness.desc': 'हामी एकता र सामूहिक विकासमा विश्वास गर्छौं। सँगै मिलेर हामी धेरै कुरा हासिल गर्न सक्छौँ।',
    'about.value.trust': 'विश्वास तथा पारदर्शिता',
    'about.value.trust.desc': 'बलियो र दीर्घकालीन सम्बन्ध निर्माण गर्न हामी इमानदारी र पारदर्शिताका साथ काम गर्छौं।',
    'about.value.empowerment': 'वित्तीय सशक्तीकरण',
    'about.value.empowerment.desc': 'राम्रो भोलिका लागि हामी नियमित बचत र समझदारीपूर्ण वित्तीय बानीलाई प्रोत्साहन गर्छौं।',
    'about.value.goal': 'हाम्रो लक्ष्य',
    'about.value.goal.desc': 'सबैजना अघि बढ्न र समृद्ध हुन सक्ने आत्मनिर्भर समुदाय निर्माण गर्नु।',
    'about.impact.heading': 'सँगै, हामी वास्तविक प्रभाव सिर्जना गर्छौं',
    'about.impact.description': 'आजको सानो बचत, भोलिको बलियो समुदाय।',
    'about.impact.activeMembers': 'सक्रिय सदस्यहरू',
    'about.impact.totalSavings': 'कुल बचत',
    'about.impact.groups': 'समूहहरू',
    'about.impact.trust': 'विश्वास तथा प्रतिबद्धता',
    'about.quote': 'एक्लै हामी थोरै मात्र गर्न सक्छौँ; सँगै मिलेर धेरै गर्न सक्छौँ।',

    'services.hero.title': 'राम्रो भोलिका लागि सँगै काम गर्दै',
    'services.hero.title.highlight': 'सँगै काम गर्दै',
    'services.hero.title.rest': 'राम्रो भोलिका लागि',
    'services.hero.description': 'हाम्रो समूहमा वित्तीय विकास विश्वास र सहकार्यबाट सुरु हुन्छ भन्ने हाम्रो विश्वास छ। नियमित बचत, जिम्मेवार ऋण र पारदर्शी वित्तीय व्यवस्थापनमार्फत हामी सदस्यहरूलाई आफ्ना लक्ष्य हासिल गर्न सक्षम बनाउँदै अझ बलियो र लचिलो समुदाय निर्माण गर्छौं।',
    'services.hero.button': 'हाम्रा सेवाहरू हेर्नुहोस्',
    'services.mission': 'हाम्रो लक्ष्य',
    'services.mission.description': 'सहकार्य, सहयोग र दिगो समाधानमार्फत मानिस र समुदायलाई सशक्त बनाउनु।',
    'services.heading.preTitle': 'हामी के गर्छौं',
    'services.heading': 'हाम्रा मुख्य सेवाहरू',
    'services.community.title': 'सामुदायिक विकास',
    'services.community.desc': 'सहभागिता र स्थानीय सशक्तीकरणमार्फत समुदायको समग्र विकासका लागि काम गर्छौं।',
    'services.education.title': 'शिक्षा सहयोग',
    'services.education.desc': 'राम्रो भविष्यका लागि स्रोत, तालिम र अवसर प्रदान गर्दै गुणस्तरीय शिक्षामा सहयोग गर्छौं।',
    'services.health.title': 'स्वास्थ्य तथा कल्याण',
    'services.health.desc': 'स्वास्थ्य सचेतना कार्यक्रम र स्वास्थ्य पहलमार्फत राम्रो स्वास्थ्य तथा कल्याण प्रवर्द्धन गर्छौं।',
    'services.livelihood.title': 'जीविकोपार्जन सहयोग',
    'services.livelihood.desc': 'दिगो आम्दानी र विकासका लागि सीप निर्माण तथा अवसरमा पहुँच बनाउन सहयोग गर्छौं।',
    'services.advocacy.title': 'वकालत तथा सचेतना',
    'services.advocacy.desc': 'महत्त्वपूर्ण सामाजिक विषयमा सचेतना फैलाउँदै सकारात्मक परिवर्तनका लागि वकालत गर्छौं।',
    'services.cta.firstTitle': 'सँगै मिलेर बनाउन सक्छौँ',
    'services.cta.firstDescription': 'बलिया समुदायहरू।',
    'services.cta.secondTitle': 'परिवर्तनको हिस्सा बन्नुहोस्।',
    'services.cta.secondDescription': 'आजै हामीसँग जोडिनुहोस्!',
    'services.cta.button': 'सहभागी हुनुहोस्',

    'members.heading': 'हाम्रा सदस्यहरू',
    'members.role': 'सदस्य',
    'members.since': 'सदस्य बनेको वर्ष',

    'contact.title': 'सम्पर्कमा',
    'contact.titleHighlight': 'रहनुहोस्',
    'contact.description': 'हामी तपाईंबाट सुन्न चाहन्छौँ। आफ्नो सन्देश पठाउनुहोस्, हामी सकेसम्म चाँडो जवाफ दिनेछौँ।',
    'contact.formTitle': 'हामीलाई सन्देश पठाउनुहोस्',
    'contact.fullName': 'पूरा नाम',
    'contact.email': 'इमेल ठेगाना',
    'contact.message': 'सन्देश',
    'contact.namePlaceholder': 'तपाईंको नाम',
    'contact.emailPlaceholder': 'तपाईंको इमेल',
    'contact.messagePlaceholder': 'हामी तपाईंलाई कसरी सहयोग गर्न सक्छौँ?',
    'contact.send': 'सन्देश पठाउनुहोस्',
    'contact.notConfigured': 'सन्देश सेवा कन्फिगर गरिएको छैन। कृपया पछि पुनः प्रयास गर्नुहोस्।',
    'contact.success': 'सन्देश सफलतापूर्वक पठाइयो!',
    'contact.failed': 'सन्देश पठाउन असफल भयो।',

    'terms.title': 'नियम तथा',
    'terms.titleHighlight': 'सर्तहरू',
    'terms.subtitle': 'हाम्रो समूहमा सहभागी हुनु अघि यी नियमहरू ध्यानपूर्वक पढ्नुहोस्।',
    'terms.savings.title': '१. बचत सम्बन्धी नियमहरू',
    'terms.savings.1': '१ गते देखि १० गते सम्म बचत गर्यो भने शुल्क लाग्दैन।',
    'terms.savings.2': '१० गते माथि बचत गर्यो भने रु. १०० शुल्क लाग्छ।',
    'terms.savings.3': '१ महिना को रू. १०० शुल्क',
    'terms.savings.4': '२ महिना को रू. २५० शुल्क',
    'terms.savings.5': '३ महिना को रू. ५०० शुल्क',
    'terms.savings.6': 'लगातार ५ महिनासम्म पैसा नतिरेमा सदस्यको खाता बन्द हुनेछ। उहाँले बचत गरेको रकम समूह सकिएपछि बिना ब्याज फिर्ता गरिनेछ।',
    'terms.newMemberLoan.title': 'ऋण चाहेको मा (नयाँ सदस्यका लागि)',
    'terms.newMemberLoan.1': '६ महिना पछि',
    'terms.loanFine.title': '२. समूहको Saving, Loan & Fine सम्बन्धमा',
    'terms.loanFine.1': 'यदि कुनै सदस्यले ऋणको किस्ता वा मासिक बचत रकम लगातार २ महिनासम्म नतिरेमा, अर्को पटकदेखि उहाँलाई समूहबाट अधिकतम रु. १५,००० सम्म मात्र ऋण प्रदान गरिनेछ। यसभन्दा बढी रकमको ऋण उपलब्ध गराइने छैन।',
    'terms.loanFine.2': 'यदि कुनै सदस्यले जरिवाना (Fine) समयमै नतिरेमा, उक्त जरिवाना रकम पहिले उहाँको वार्षिक ब्याजबाट कट्टा गरिनेछ। यदि वार्षिक ब्याजले जरिवाना रकम नपुगेमा, बाँकी जरिवाना रकम उहाँको मूल बचत रकमबाट कट्टा गरिनेछ।',
    'terms.loanFine.3': 'यदि कसैलाई समस्या छ, भने एक चोटि समूहको Group मा Information गरिदिनु होला, हामी हेरेर केही Decision लिन्छौं।',
    'terms.meeting.title': '३. Meeting तथा Loan सम्बन्धी नियमहरू',
    'terms.meeting.1': 'हामी हरेर महिनामा एक चोटि Meeting मा बस्छौं, पैसा Deposit भए पछि शनिबारको दिन।',
    'terms.meeting.2': 'यदि कसैलाई Loan चाहिएमा ७ वा १० दिन अगाडि समूहमा Information गरिदिनु होला।',
    'terms.meeting.3': 'हामी प्रत्येक महिना रू ५० छुटयाएको छौं, समूहको Member लाई Notice गराउनको लागि।',
    'terms.meeting.4': 'Loan लिनु अगाडि Service Charge Deposit (१५०) गरिदिनु होला।',
    'terms.interest.title': '४. ब्याज दर (Interest Rate)',
    'terms.interest.1': 'रू. ० देखि रू. ५०,००० सम्मको ऋण बार्षिक ब्याज ९% लाग्दछ।',
    'terms.interest.2': 'रू. ५०,००० देखि माथिको ऋणको ब्याज १२% लाग्दछ।',
    'terms.example.for': 'उदाहरणको लागि',
    'terms.interest.example': 'रू ७,००,००० ऋण लिएको भने — रू ५,०,००० को बार्षिक ९% + रू २,०,००० को १२% लाग्दछ।',
    'terms.newLoan.title': '५. नयाँ सदस्य र ऋण सुविधा',
    'terms.newLoan.1': 'हाम्रो समूहमा जोडेको नयाँ सदस्य ६ महिना सम्म ऋण निकाल्न मिल्दैन।',
    'terms.newLoan.2': 'यदि कुनै सदस्यले लगातार ६ महिनासम्म नियमित रूपमा बचत (Saving) गरेमा र आफ्नो बचत राम्रोसँग कायम राखेमा, उहाँले आवश्यकताअनुसार ऋण प्राप्त गर्न सक्नुहुनेछ।',
    'terms.profit.title': '६. नाफा वितरण तथा Secondary Saving',
    'terms.profit.1': 'हाम्रो समूहको नाममा बार्षिक Total Profit बाट ५% Saving गर्ने निर्णय गरेको छ।',
    'terms.profit.2': 'जसले हिसाब किताब गरिराखेको छ भने बार्षिक Total Profit बाट २% हुने गरी दिने निर्णय गरेको छ।',
    'terms.profit.3': 'Secondary Saving मा नयाँ व्यक्ति join २०८२/१०/०१ गते देखि २०८३/०९/३० गते सम्म कुनै शुल्क लाग्दैन यदि त्योभन्दा बढी भएमा रु ५० को दरले शुल्क लाग्ने निर्णय गरिएको।',
    'terms.secondaryFee.title': 'Secondary Saving शुल्क सम्बन्धमा',
    'terms.secondaryFee.1': 'पहिलो महिनामा saving छुटे वा नभरेमा रु २० शुल्क लाग्दैछ।',
    'terms.secondaryFee.2': 'दोस्रो महिनामा रु ५० को शुल्क लाग्दछ।',
    'terms.secondaryFee.3': 'तेस्रो महिनामा रु १०० को शुल्क लाग्दछ।',
    'terms.secondaryNewLoan.title': '७. Secondary नयाँ Member को Loan',
    'terms.secondaryNewLoan.1': 'सदस्य बनेको ६ महिना पूरा भएपछि Secondary Loan अन्तर्गत अधिकतम रु. ७,००० सम्म ऋण लिन पाइनेछ।',
    'terms.secondaryInterest.title': '८. Secondary को Loan र Interest सम्बन्ध',
    'terms.secondaryInterest.1': 'रु १,००० देखि रु १०,००० सम्मको interest वार्षिक ९% लागिनेछ।',
    'terms.secondaryInterest.2': 'रु १० हजार देखि माथिको interest १२% लागिनेछ।',
    'terms.secondaryInterest.example.1': 'रु २०,००० को Loan — रु १० हजारको वार्षिक ९% + बाँकी १० हजारको १२% लाग्दैछ।',
    'terms.secondaryInterest.example.2': '१ वर्षमा Loan चुक्ता गर्न सक्नुहुन्न भने जति Loan रकम रहेकोमा त्यतिको interest जति Renewal लाग्दैछ।',
    'terms.share.title': '९. सेयर बजार सम्बन्धको',
    'terms.share.1': 'हाम्रो समूहको लागि Demat उपलब्ध गराउनुभएका सदस्यहरूको Demat मार्फत खरिद गरिएको सेयर बिक्री गर्दा नाफा भएमा, प्राप्त नाफाको १०% सम्बन्धित सदस्यलाई प्रदान गरिनेछ।',
    'terms.share.2': 'जुन सदस्यको नाममा हाम्रो समूहले Demat खाता खोलेको छ, उहाँले भविष्यमा उक्त Demat खाता व्यक्तिगत रूपमा प्रयोग गरी नाफा कमाउनुभयो भने, प्राप्त नाफाको १०% हाम्रो समूहको बचत (Saving) मा जम्मा गर्नुपर्ने निर्णय गरिएको छ।',
    'terms.share.3': 'सेयरको लागि पैसा पठाएको त्यो पैसा आफ्नो Personal खर्च नगरिदिनुहोला यही अनुरोध छ।',
    'terms.date': '२०८२/०९/२०',
    'terms.thankYou': 'धन्यवाद',
  },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

function getInitialLanguage(): Language {
  if (typeof window === 'undefined') return 'en';

  const savedLanguage = window.localStorage.getItem('hamro-samuh-language');
  return savedLanguage === 'np' ? 'np' : 'en';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(getInitialLanguage);

  useEffect(() => {
    window.localStorage.setItem('hamro-samuh-language', language);
    document.documentElement.lang = language === 'np' ? 'ne' : 'en';
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(current => current === 'en' ? 'np' : 'en');
  };

  const t = (key: string) => translations[language][key] ?? translations.en[key] ?? key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }

  return context;
}
